site_name: GoElites Wiki
repo_url: https://github.com/y1n/GoElites.Wiki
pages:
- Home: index.md
- Principles:
    - Community Guidelines: CommunityPrinciples/CommunityGuidelines.md
    - Support Guidelines: CommunityPrinciples/SupportGuidelines.md
- Getting Started:
    - Installing GoElites: GettingStarted/Installation.md
    - Features Explained: GettingStarted/Features.md
    - Supported Champions: GettingStarted/SupportedChampions.md
    - Frequently Asked Questions: GettingStarted/FrequentlyAskedQuestions.md
- Troubleshooting:
    - How to submit a support ticket: Troubleshooting/TroubleshootingReportGuide.md
    - Website Support: Troubleshooting/WebsiteTroubleshooting.md
    - Application Support: Troubleshooting/ApplicationTroubleshooting.md
    
theme: readthedocs